import { Matches } from "./models/Matches";

export const CL_DATA: Matches = {
  "filters": {
    "season": "2024"
  },
  "resultSet": {
    "count": 18,
    "first": "2024-10-23",
    "last": "2024-11-05",
    "played": 9
  },
  "competition": {
    "id": 2001,
    "name": "UEFA Champions League",
    "code": "CL",
    "type": "CUP",
    "emblem": "https://crests.football-data.org/CL.png"
  },
  "matches": [
    {
      "area": {
        "id": 2077,
        "name": "Europe",
        "code": "EUR",
        "flag": "https://crests.football-data.org/EUR.svg"
      },
      "competition": {
        "id": 2001,
        "name": "UEFA Champions League",
        "code": "CL",
        "type": "CUP",
        "emblem": "https://crests.football-data.org/CL.png"
      },
      "season": {
        "id": 2350,
        "startDate": "2024-09-17",
        "endDate": "2025-05-31",
        "currentMatchday": 4,
        "winner": undefined
      },
      "id": 523986,
      "utcDate": "2024-10-23T19:00:00Z",
      "status": "FINISHED",
      "matchday": 3,
      "stage": "LEAGUE_STAGE",
      "group": undefined,
      "lastUpdated": "2024-10-27T15:20:28Z",
      "homeTeam": {
        "id": 1903,
        "name": "Sport Lisboa e Benfica",
        "shortName": "SL Benfica",
        "tla": "BEN",
        "crest": "https://crests.football-data.org/1903.png"
      },
      "awayTeam": {
        "id": 675,
        "name": "Feyenoord Rotterdam",
        "shortName": "Feyenoord",
        "tla": "FEY",
        "crest": "https://crests.football-data.org/675.png"
      },
      "score": {
        "winner": "AWAY_TEAM",
        "duration": "REGULAR",
        "fullTime": {
          "home": 1,
          "away": 3
        },
        "halfTime": {
          "home": 0,
          "away": 2
        }
      },
      "odds": {
        "msg": "Activate Odds-Package in User-Panel to retrieve odds."
      },
      "referees": [
        {
          "id": 214424,
          "name": "Halil Meler",
          "type": "REFEREE",
          "nationality": "Turkey"
        }
      ]
    },
    {
      "area": {
        "id": 2077,
        "name": "Europe",
        "code": "EUR",
        "flag": "https://crests.football-data.org/EUR.svg"
      },
      "competition": {
        "id": 2001,
        "name": "UEFA Champions League",
        "code": "CL",
        "type": "CUP",
        "emblem": "https://crests.football-data.org/CL.png"
      },
      "season": {
        "id": 2350,
        "startDate": "2024-09-17",
        "endDate": "2025-05-31",
        "currentMatchday": 4,
        "winner": undefined
      },
      "id": 524026,
      "utcDate": "2024-10-23T19:00:00Z",
      "status": "FINISHED",
      "matchday": 3,
      "stage": "LEAGUE_STAGE",
      "group": undefined,
      "lastUpdated": "2024-10-27T15:20:28Z",
      "homeTeam": {
        "id": 1877,
        "name": "FC Red Bull Salzburg",
        "shortName": "RB Salzburg",
        "tla": "RBS",
        "crest": "https://crests.football-data.org/1877.png"
      },
      "awayTeam": {
        "id": 755,
        "name": "GNK Dinamo Zagreb",
        "shortName": "Dinamo Zagreb",
        "tla": "DIN",
        "crest": "https://crests.football-data.org/755.png"
      },
      "score": {
        "winner": "AWAY_TEAM",
        "duration": "REGULAR",
        "fullTime": {
          "home": 0,
          "away": 2
        },
        "halfTime": {
          "home": 0,
          "away": 0
        }
      },
      "odds": {
        "msg": "Activate Odds-Package in User-Panel to retrieve odds."
      },
      "referees": [
        {
          "id": 43899,
          "name": "Danny Makkelie",
          "type": "REFEREE",
          "nationality": "Netherlands"
        }
      ]
    },
    {
      "area": {
        "id": 2077,
        "name": "Europe",
        "code": "EUR",
        "flag": "https://crests.football-data.org/EUR.svg"
      },
      "competition": {
        "id": 2001,
        "name": "UEFA Champions League",
        "code": "CL",
        "type": "CUP",
        "emblem": "https://crests.football-data.org/CL.png"
      },
      "season": {
        "id": 2350,
        "startDate": "2024-09-17",
        "endDate": "2025-05-31",
        "currentMatchday": 4,
        "winner": undefined
      },
      "id": 524004,
      "utcDate": "2024-11-05T20:00:00Z",
      "status": "TIMED",
      "matchday": 4,
      "stage": "LEAGUE_STAGE",
      "group": undefined,
      "lastUpdated": "2024-08-31T17:14:30Z",
      "homeTeam": {
        "id": 732,
        "name": "Celtic FC",
        "shortName": "Celtic",
        "tla": "CEL",
        "crest": "https://crests.football-data.org/732.png"
      },
      "awayTeam": {
        "id": 721,
        "name": "RB Leipzig",
        "shortName": "RB Leipzig",
        "tla": "RBL",
        "crest": "https://crests.football-data.org/721.png"
      },
      "score": {
        "winner": undefined,
        "duration": "REGULAR",
        "fullTime": {
          "home": undefined,
          "away": undefined
        },
        "halfTime": {
          "home": undefined,
          "away": undefined
        }
      },
      "odds": {
        "msg": "Activate Odds-Package in User-Panel to retrieve odds."
      },
      "referees": []
    },
    {
      "area": {
        "id": 2077,
        "name": "Europe",
        "code": "EUR",
        "flag": "https://crests.football-data.org/EUR.svg"
      },
      "competition": {
        "id": 2001,
        "name": "UEFA Champions League",
        "code": "CL",
        "type": "CUP",
        "emblem": "https://crests.football-data.org/CL.png"
      },
      "season": {
        "id": 2350,
        "startDate": "2024-09-17",
        "endDate": "2025-05-31",
        "currentMatchday": 4,
        "winner": undefined
      },
      "id": 524017,
      "utcDate": "2024-11-05T20:00:00Z",
      "status": "TIMED",
      "matchday": 4,
      "stage": "LEAGUE_STAGE",
      "group": undefined,
      "lastUpdated": "2024-08-31T17:14:30Z",
      "homeTeam": {
        "id": 521,
        "name": "Lille OSC",
        "shortName": "Lille",
        "tla": "LIL",
        "crest": "https://crests.football-data.org/521.png"
      },
      "awayTeam": {
        "id": 109,
        "name": "Juventus FC",
        "shortName": "Juventus",
        "tla": "JUV",
        "crest": "https://crests.football-data.org/109.png"
      },
      "score": {
        "winner": undefined,
        "duration": "REGULAR",
        "fullTime": {
          "home": undefined,
          "away": undefined
        },
        "halfTime": {
          "home": undefined,
          "away": undefined
        }
      },
      "odds": {
        "msg": "Activate Odds-Package in User-Panel to retrieve odds."
      },
      "referees": []
    }
  ]
}
