import { Matches } from "./models/Matches";

export const PL_DATA: Matches = {
  "filters": {
    "season": "2024"
  },
  "resultSet": {
    "count": 20,
    "first": "2024-10-25",
    "last": "2024-11-04",
    "played": 10
  },
  "competition": {
    "id": 2021,
    "name": "Premier League",
    "code": "PL",
    "type": "LEAGUE",
    "emblem": "https://crests.football-data.org/PL.png"
  },
  "matches": [
    {
      "area": {
        "id": 2072,
        "name": "England",
        "code": "ENG",
        "flag": "https://crests.football-data.org/770.svg"
      },
      "competition": {
        "id": 2021,
        "name": "Premier League",
        "code": "PL",
        "type": "LEAGUE",
        "emblem": "https://crests.football-data.org/PL.png"
      },
      "season": {
        "id": 2287,
        "startDate": "2024-08-16",
        "endDate": "2025-05-25",
        "currentMatchday": 9,
        "winner": undefined
      },
      "id": 497497,
      "utcDate": "2024-10-25T19:00:00Z",
      "status": "FINISHED",
      "matchday": 9,
      "stage": "REGULAR_SEASON",
      "group": undefined,
      "lastUpdated": "2024-10-27T10:20:44Z",
      "homeTeam": {
        "id": 338,
        "name": "Leicester City FC",
        "shortName": "Leicester City",
        "tla": "LEI",
        "crest": "https://crests.football-data.org/338.png"
      },
      "awayTeam": {
        "id": 351,
        "name": "Nottingham Forest FC",
        "shortName": "Nottingham",
        "tla": "NOT",
        "crest": "https://crests.football-data.org/351.png"
      },
      "score": {
        "winner": "AWAY_TEAM",
        "duration": "REGULAR",
        "fullTime": {
          "home": 1,
          "away": 3
        },
        "halfTime": {
          "home": 1,
          "away": 1
        }
      },
      "odds": {
        "msg": "Activate Odds-Package in User-Panel to retrieve odds."
      },
      "referees": [
        {
          "id": 11585,
          "name": "Craig Pawson",
          "type": "REFEREE",
          "nationality": "England"
        }
      ]
    },
    {
      "area": {
        "id": 2072,
        "name": "England",
        "code": "ENG",
        "flag": "https://crests.football-data.org/770.svg"
      },
      "competition": {
        "id": 2021,
        "name": "Premier League",
        "code": "PL",
        "type": "LEAGUE",
        "emblem": "https://crests.football-data.org/PL.png"
      },
      "season": {
        "id": 2287,
        "startDate": "2024-08-16",
        "endDate": "2025-05-25",
        "currentMatchday": 9,
        "winner": undefined
      },
      "id": 497491,
      "utcDate": "2024-10-26T14:00:00Z",
      "status": "FINISHED",
      "matchday": 9,
      "stage": "REGULAR_SEASON",
      "group": undefined,
      "lastUpdated": "2024-10-27T10:20:44Z",
      "homeTeam": {
        "id": 58,
        "name": "Aston Villa FC",
        "shortName": "Aston Villa",
        "tla": "AVL",
        "crest": "https://crests.football-data.org/58.png"
      },
      "awayTeam": {
        "id": 1044,
        "name": "AFC Bournemouth",
        "shortName": "Bournemouth",
        "tla": "BOU",
        "crest": "https://crests.football-data.org/bournemouth.png"
      },
      "score": {
        "winner": "DRAW",
        "duration": "REGULAR",
        "fullTime": {
          "home": 1,
          "away": 1
        },
        "halfTime": {
          "home": 0,
          "away": 0
        }
      },
      "odds": {
        "msg": "Activate Odds-Package in User-Panel to retrieve odds."
      },
      "referees": [
        {
          "id": 11423,
          "name": "Andy Madley",
          "type": "REFEREE",
          "nationality": "England"
        }
      ]
    },
    {
      "area": {
        "id": 2072,
        "name": "England",
        "code": "ENG",
        "flag": "https://crests.football-data.org/770.svg"
      },
      "competition": {
        "id": 2021,
        "name": "Premier League",
        "code": "PL",
        "type": "LEAGUE",
        "emblem": "https://crests.football-data.org/PL.png"
      },
      "season": {
        "id": 2287,
        "startDate": "2024-08-16",
        "endDate": "2025-05-25",
        "currentMatchday": 9,
        "winner": undefined
      },
      "id": 497504,
      "utcDate": "2024-11-03T16:30:00Z",
      "status": "TIMED",
      "matchday": 10,
      "stage": "REGULAR_SEASON",
      "group": undefined,
      "lastUpdated": "2024-10-28T01:32:11Z",
      "homeTeam": {
        "id": 66,
        "name": "Manchester United FC",
        "shortName": "Man United",
        "tla": "MUN",
        "crest": "https://crests.football-data.org/66.png"
      },
      "awayTeam": {
        "id": 61,
        "name": "Chelsea FC",
        "shortName": "Chelsea",
        "tla": "CHE",
        "crest": "https://crests.football-data.org/61.png"
      },
      "score": {
        "winner": undefined,
        "duration": "REGULAR",
        "fullTime": {
          "home": undefined,
          "away": undefined
        },
        "halfTime": {
          "home": undefined,
          "away": undefined
        }
      },
      "odds": {
        "msg": "Activate Odds-Package in User-Panel to retrieve odds."
      },
      "referees": []
    },
    {
      "area": {
        "id": 2072,
        "name": "England",
        "code": "ENG",
        "flag": "https://crests.football-data.org/770.svg"
      },
      "competition": {
        "id": 2021,
        "name": "Premier League",
        "code": "PL",
        "type": "LEAGUE",
        "emblem": "https://crests.football-data.org/PL.png"
      },
      "season": {
        "id": 2287,
        "startDate": "2024-08-16",
        "endDate": "2025-05-25",
        "currentMatchday": 9,
        "winner": undefined
      },
      "id": 497501,
      "utcDate": "2024-11-04T20:00:00Z",
      "status": "TIMED",
      "matchday": 10,
      "stage": "REGULAR_SEASON",
      "group": undefined,
      "lastUpdated": "2024-09-17T10:20:49Z",
      "homeTeam": {
        "id": 63,
        "name": "Fulham FC",
        "shortName": "Fulham",
        "tla": "FUL",
        "crest": "https://crests.football-data.org/63.png"
      },
      "awayTeam": {
        "id": 402,
        "name": "Brentford FC",
        "shortName": "Brentford",
        "tla": "BRE",
        "crest": "https://crests.football-data.org/402.png"
      },
      "score": {
        "winner": undefined,
        "duration": "REGULAR",
        "fullTime": {
          "home": undefined,
          "away": undefined
        },
        "halfTime": {
          "home": undefined,
          "away": undefined
        }
      },
      "odds": {
        "msg": "Activate Odds-Package in User-Panel to retrieve odds."
      },
      "referees": []
    }
  ]
}