import { Matches } from "./models/Matches";

export const PL_DATA: Matches = {
  "filters": { "season": "2024" },
  "resultSet": {
    "count": 40,
    "first": "2024-11-02",
    "last": "2024-12-01",
    "played": 0
  },
  "competition": {
    "id": 2021,
    "name": "Premier League",
    "code": "PL",
    "type": "LEAGUE",
    "emblem": "https://crests.football-data.org/PL.png"
  },
  "matches": [
    {
      "area": {
        "id": 2077,
        "name": "Europe",
        "code": "EUR",
        "flag": "https://crests.football-data.org/EUR.svg"
      },
      "competition": {
        "id": 2001,
        "name": "UEFA Champions League",
        "code": "CL",
        "type": "CUP",
        "emblem": "https://crests.football-data.org/CL.png"
      },
      "season": {
        "id": 2350,
        "startDate": "2024-09-17",
        "endDate": "2025-05-31",
        "currentMatchday": 4,
        "winner": undefined
      },
      "id": 523986,
      "utcDate": "2024-10-23T19:00:00Z",
      "status": "FINISHED",
      "matchday": 3,
      "stage": "LEAGUE_STAGE",
      "group": undefined,
      "lastUpdated": "2024-10-27T15:20:28Z",
      "homeTeam": {
        "id": 1903,
        "name": "Sport Lisboa e Benfica",
        "shortName": "SL Benfica",
        "tla": "BEN",
        "crest": "https://crests.football-data.org/1903.png"
      },
      "awayTeam": {
        "id": 675,
        "name": "Feyenoord Rotterdam",
        "shortName": "Feyenoord",
        "tla": "FEY",
        "crest": "https://crests.football-data.org/675.png"
      },
      "score": {
        "winner": "AWAY_TEAM",
        "duration": "REGULAR",
        "fullTime": {
          "home": 1,
          "away": 3
        },
        "halfTime": {
          "home": 0,
          "away": 2
        }
      },
      "odds": {
        "msg": "Activate Odds-Package in User-Panel to retrieve odds."
      },
      "referees": [
        {
          "id": 214424,
          "name": "Halil Meler",
          "type": "REFEREE",
          "nationality": "Turkey"
        }
      ]
    },
    {
    "area": {
      "id": 2072,
      "name": "England",
      "code": "ENG",
      "flag": "https://crests.football-data.org/770.svg"
    },
    "competition": {
      "id": 2021,
      "name": "Premier League",
      "code": "PL",
      "type": "LEAGUE",
      "emblem": "https://crests.football-data.org/PL.png"
    },
    "season": {
      "id": 2287,
      "startDate": "2024-08-16",
      "endDate": "2025-05-25",
      "currentMatchday": 10,
      "winner": undefined
    },
    "id": 497505,
    "utcDate": "2024-11-02T12:30:00Z",
    "status": "TIMED",
    "matchday": 10,
    "stage": "REGULAR_SEASON",
    "group": undefined,
    "lastUpdated": "2024-10-28T01:32:06Z",
    "homeTeam": {
      "id": 67,
      "name": "Newcastle United FC",
      "shortName": "Newcastle",
      "tla": "NEW",
      "crest": "https://crests.football-data.org/67.png"
    },
    "awayTeam": {
      "id": 57,
      "name": "Arsenal FC",
      "shortName": "Arsenal",
      "tla": "ARS",
      "crest": "https://crests.football-data.org/57.png"
    },
    "score": {
      "winner": undefined,
      "duration": "REGULAR",
      "fullTime": { "home": undefined, "away": undefined },
      "halfTime": { "home": undefined, "away": undefined }
    },
    "odds": { "msg": "Activate Odds-Package in User-Panel to retrieve odds." },
    "referees": []
  }, {
    "area": {
      "id": 2072,
      "name": "England",
      "code": "ENG",
      "flag": "https://crests.football-data.org/770.svg"
    },
    "competition": {
      "id": 2021,
      "name": "Premier League",
      "code": "PL",
      "type": "LEAGUE",
      "emblem": "https://crests.football-data.org/PL.png"
    },
    "season": {
      "id": 2287,
      "startDate": "2024-08-16",
      "endDate": "2025-05-25",
      "currentMatchday": 10,
      "winner": undefined
    },
    "id": 497500,
    "utcDate": "2024-11-02T15:00:00Z",
    "status": "TIMED",
    "matchday": 10,
    "stage": "REGULAR_SEASON",
    "group": undefined,
    "lastUpdated": "2024-11-01T00:20:45Z",
    "homeTeam": {
      "id": 1044,
      "name": "AFC Bournemouth",
      "shortName": "Bournemouth",
      "tla": "BOU",
      "crest": "https://crests.football-data.org/bournemouth.png"
    },
    "awayTeam": {
      "id": 65,
      "name": "Manchester City FC",
      "shortName": "Man City",
      "tla": "MCI",
      "crest": "https://crests.football-data.org/65.png"
    },
    "score": {
      "winner": undefined,
      "duration": "REGULAR",
      "fullTime": { "home": undefined, "away": undefined },
      "halfTime": { "home": undefined, "away": undefined }
    },
    "odds": { "msg": "Activate Odds-Package in User-Panel to retrieve odds." },
    "referees": []
  }, {
    "area": {
      "id": 2072,
      "name": "England",
      "code": "ENG",
      "flag": "https://crests.football-data.org/770.svg"
    },
    "competition": {
      "id": 2021,
      "name": "Premier League",
      "code": "PL",
      "type": "LEAGUE",
      "emblem": "https://crests.football-data.org/PL.png"
    },
    "season": {
      "id": 2287,
      "startDate": "2024-08-16",
      "endDate": "2025-05-25",
      "currentMatchday": 10,
      "winner": undefined
    },
    "id": 497502,
    "utcDate": "2024-11-02T15:00:00Z",
    "status": "TIMED",
    "matchday": 10,
    "stage": "REGULAR_SEASON",
    "group": undefined,
    "lastUpdated": "2024-11-01T00:20:45Z",
    "homeTeam": {
      "id": 349,
      "name": "Ipswich Town FC",
      "shortName": "Ipswich Town",
      "tla": "IPS",
      "crest": "https://crests.football-data.org/349.png"
    },
    "awayTeam": {
      "id": 338,
      "name": "Leicester City FC",
      "shortName": "Leicester City",
      "tla": "LEI",
      "crest": "https://crests.football-data.org/338.png"
    },
    "score": {
      "winner": undefined,
      "duration": "REGULAR",
      "fullTime": { "home": undefined, "away": undefined },
      "halfTime": { "home": undefined, "away": undefined }
    },
    "odds": { "msg": "Activate Odds-Package in User-Panel to retrieve odds." },
    "referees": []
  }, {
    "area": {
      "id": 2072,
      "name": "England",
      "code": "ENG",
      "flag": "https://crests.football-data.org/770.svg"
    },
    "competition": {
      "id": 2021,
      "name": "Premier League",
      "code": "PL",
      "type": "LEAGUE",
      "emblem": "https://crests.football-data.org/PL.png"
    },
    "season": {
      "id": 2287,
      "startDate": "2024-08-16",
      "endDate": "2025-05-25",
      "currentMatchday": 10,
      "winner": undefined
    },
    "id": 497503,
    "utcDate": "2024-11-02T15:00:00Z",
    "status": "TIMED",
    "matchday": 10,
    "stage": "REGULAR_SEASON",
    "group": undefined,
    "lastUpdated": "2024-10-28T01:32:08Z",
    "homeTeam": {
      "id": 64,
      "name": "Liverpool FC",
      "shortName": "Liverpool",
      "tla": "LIV",
      "crest": "https://crests.football-data.org/64.png"
    },
    "awayTeam": {
      "id": 397,
      "name": "Brighton & Hove Albion FC",
      "shortName": "Brighton Hove",
      "tla": "BHA",
      "crest": "https://crests.football-data.org/397.png"
    },
    "score": {
      "winner": undefined,
      "duration": "REGULAR",
      "fullTime": { "home": undefined, "away": undefined },
      "halfTime": { "home": undefined, "away": undefined }
    },
    "odds": { "msg": "Activate Odds-Package in User-Panel to retrieve odds." }
  }]
}
